### ISSUE TITLE
CORS request blocked

### ISSUE THREAD

**Issue by liondy** [liondy/covid19-tracker-website#8]
Beberapa API yang akan digunakan mendapatkan error `CORS request blocked` seperti:
- [https://data.covid19.go.id/public/api/prov.json](https://data.covid19.go.id/public/api/prov.json)
- [https://dekontaminasi.com/api/id/covid19/hospitals](https://dekontaminasi.com/api/id/covid19/hospitals)

Butuh cari API lain untuk nge fetch data provinsi. Tolong kasih saran2nya di kolom komentar ya.. @dian26swas @Ttanus @Obolsuro

**Comment by liondy** [comment]
Ini alasannya karena API nya tidak memperbolehkan untuk mengambil data dari domain luar. Untuk solusinya, harus ditambahkan `headers: {'Access-Control-Allow-Origin': '*'}` di server tempat API nya. Berhubung API nya kita pakai `third-party API` dan bukan buat sendiri, maka kita gabisa maksa fetch dari situ, jadi solusi kedua adalah ganti API nya.

**Comment by Ttanus** [comment]
kalo ganti jadi https://lintangwisesa.github.io/Indonesia-Covid19-Maps/api.html gimana?

**Comment by liondy** [comment]
yap bisa @Ttanus

**Comment by liondy** [comment]
@Ttanus hold dulu, ini datanya palsu

**Comment by liondy** [comment]
@Ttanus datanya di hard-code euy..

**Comment by liondy** [comment]
Terakhir di update tanggal 30 April 2020

**Comment by Ttanus** [comment]
hmm... kalo pake https://kawalcorona.com/api/ aja gmn?

**Comment by liondy** [comment]
Coba liat screenshot ini, kalau lagi di laptop coba convert si LastUpdate nya (dalam bentuk timestamp), ubah ke Date biasa. Barusan gw pakai online converter last update nya 13 September... 
![Screenshot_20201229-180810_Chrome.jpg](https://user-images.githubusercontent.com/44316758/103279660-da6d8c80-4a00-11eb-9592-3b711d3773d9.jpg)

**Comment by Ttanus** [comment]
gpp lah kayaknya, ntar ditampilin aja, yg penting mereka ga hardcode juga... Siapa tau pas dipake mereka update lagi

**Comment by liondy** [comment]
OK silahkan saja ya

**Comment by liondy** [comment]
Update..silakan coba pakai API ini: [https://services5.arcgis.com/VS6HdKS0VfIhv8Ct/arcgis/rest/services/COVID19_Indonesia_per_Provinsi/FeatureServer/0/query?where=1%3D1&outFields=*&outSR=4326&f=json](https://services5.arcgis.com/VS6HdKS0VfIhv8Ct/arcgis/rest/services/COVID19_Indonesia_per_Provinsi/FeatureServer/0/query?where=1%3D1&outFields=*&outSR=4326&f=json) @Ttanus

**Comment by liondy** [comment]
untuk returnnya bisa langsung pakai `return response.data.features`

**Comment by liondy** [comment]
untuk masalah CORS Request Blocked, sementara diatasi pakai `proxy`, gw tambahkan opsi `proxy` di [package.json](https://github.com/liondy/covid19-tracker-website/blob/master/package.json).

**Comment by liondy** [comment]
[UPDATE] untuk masalah CORS, gw jadinya bikin service sendiri yang gw host di [vercel](https://vercel.com). Ini jadinya `serverless Node.JS API`. Jadi, untuk ke depannya, `"proxy": "https://dekontaminasi.com",` bisa dihapus aja dari file [package.json](https://github.com/liondy/covid19-tracker-website/blob/master/package.json) dan pemanggilan API di file [Api.js](https://github.com/liondy/covid19-tracker-website/blob/master/src/api/Api.js) bisa deperti biasa.

Untuk link API nya: https://covid-19-indonesia-hospital.liondy.vercel.app/api

**Comment by liondy** [comment]
~~Untuk link API nya: https://covid-19-indonesia-hospital.liondy.vercel.app/api~~
Sorry, untuk link API nya: [https://serverless-covid19-indonesia-api.liondy.vercel.app/](https://serverless-covid19-indonesia-api.liondy.vercel.app/)

**Comment by Ttanus** [comment]
Untuk Provinsi, API yang dipakai adalah https://serverless-covid19-indonesia-api.liondy.vercel.app/ dan https://services5.arcgis.com/VS6HdKS0VfIhv8Ct/arcgis/rest/services/COVID19_Indonesia_per_Provinsi/FeatureServer/0/query?where=1%3D1&outFields=*&outSR=4326&f=json
